"""
Trains architecture.PlateGNN on simulated (sensor readings -> true state)
pairs generated by the biology + sensor layers. Ground truth is fully known
(this is the advantage of synthetic data), so labels are:

  - health_score_true = 1 - (0.7*stress_level + 0.3*warburg_index), clipped
    to [0, 1] -- combines the latent decline process with how "Warburg-like"
    the metabolism currently is, since that's what actually drives the
    sensor pattern the model has to read.
  - o2_consumption / lactate_production, min-max normalized using the same
    calibration sweep constraints.py fits the stoichiometric line from.

Each training example is one full-plate snapshot (all N wells at one
timestep, with each well's last WINDOW sensor readings) so the GATv2 layers
train against real cross-well graph structure, not isolated wells.

Run directly to train both ablation arms (with/without the hard consistency
constraint):
    .venv/bin/python -m backend.gnn.train
"""
import json
import time

import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

from backend.biology.organoid_trajectory import N_STEPS, simulate_plate
from backend.config import CHECKPOINT_DIR, SENSOR_TYPES, WELL_IDS
from backend.gnn.architecture import CAUSE_CLASSES, DEFAULT_WINDOW, PlateGNN
from backend.gnn.constraints import calibrate_stoichiometry, stoichiometric_consistency_penalty
from backend.gnn.plate_graph import PLATE_ADJACENCY
from backend.sensors.sensor_model import trajectory_to_readings

N_TRAIN_PLATES = 16
N_VAL_PLATES = 4
TIME_STRIDE = 2          # subsample timesteps to keep the dataset a manageable size
BATCH_SIZE = 16
N_EPOCHS = 20
LR = 1e-3
CONSTRAINT_WEIGHT = 0.3
AUX_WEIGHT = 0.5
CAUSE_WEIGHT = 0.7

_CAUSE_TO_IDX = {name: i for i, name in enumerate(CAUSE_CLASSES)}


def _build_plate_tensors(base_seed: int, fit) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """One plate -> (n_snapshots, N, WINDOW, 4) inputs + 4 label tensors, all snapshots from that plate."""
    plate = simulate_plate(WELL_IDS, base_seed=base_seed)
    readings = {wid: trajectory_to_readings(traj, seed=base_seed * 7919 + i) for i, (wid, traj) in enumerate(plate.items())}

    sensor_stack = np.stack(
        [np.stack([getattr(readings[wid], s) for s in SENSOR_TYPES], axis=-1) for wid in WELL_IDS],
        axis=0,
    )  # (N, T, 4)

    health_true = np.stack(
        [np.clip(1.0 - (0.7 * plate[wid].stress_level + 0.3 * plate[wid].warburg_index), 0.0, 1.0) for wid in WELL_IDS],
        axis=0,
    )  # (N, T)
    o2_true = np.stack([plate[wid].o2_consumption for wid in WELL_IDS], axis=0)
    lac_true = np.stack([plate[wid].lactate_production for wid in WELL_IDS], axis=0)
    o2_norm = np.clip((o2_true - fit.o2_min) / (fit.o2_max - fit.o2_min + 1e-9), 0.0, 1.0)
    lac_norm = np.clip((lac_true - fit.lactate_min) / (fit.lactate_max - fit.lactate_min + 1e-9), 0.0, 1.0)

    # Cause label per (well, timestep): "none" before decline latches on,
    # then the well's recorded root cause for the rest of the trajectory --
    # decline_dynamics.py fixes limiting_factor the moment decline_active
    # first turns True, so it's already known at every True timestep.
    #
    # Tried adding a "grace period" (delaying the label until the physical
    # signature has visibly developed, since e.g. enzyme_activity is still
    # >95% intact at an adverse-event well's exact onset) -- it traded one
    # problem for another (adverse-event accuracy roughly doubled, but
    # glucose accuracy collapsed from 37% to 7%), for the same ~46% overall
    # accuracy either way. Reverted: this version's per-class balance
    # (oxygen 82%, glucose 37%, adverse_event 21%) beats the alternative's
    # (79%/7%/44%) as a real fix rather than a shell game between classes.
    cause_idx = np.zeros((len(WELL_IDS), N_STEPS), dtype=np.int64)
    for wi, wid in enumerate(WELL_IDS):
        traj = plate[wid]
        if traj.limiting_factor is not None:
            cause_idx[wi, traj.decline_active] = _CAUSE_TO_IDX[traj.limiting_factor]

    xs, ys_health, ys_o2, ys_lac, ys_cause = [], [], [], [], []
    for t in range(DEFAULT_WINDOW, N_STEPS, TIME_STRIDE):
        xs.append(sensor_stack[:, t - DEFAULT_WINDOW:t, :])
        ys_health.append(health_true[:, t])
        ys_o2.append(o2_norm[:, t])
        ys_lac.append(lac_norm[:, t])
        ys_cause.append(cause_idx[:, t])

    return (
        torch.tensor(np.stack(xs), dtype=torch.float32),
        torch.tensor(np.stack(ys_health), dtype=torch.float32),
        torch.tensor(np.stack(ys_o2), dtype=torch.float32),
        torch.tensor(np.stack(ys_lac), dtype=torch.float32),
        torch.tensor(np.stack(ys_cause), dtype=torch.long),
    )


def build_dataset(n_plates: int, seed_offset: int, fit):
    xs, hs, o2s, lacs, causes = [], [], [], [], []
    for i in range(n_plates):
        x, h, o2, lac, cause = _build_plate_tensors(base_seed=seed_offset + i, fit=fit)
        xs.append(x)
        hs.append(h)
        o2s.append(o2)
        lacs.append(lac)
        causes.append(cause)
    return (torch.cat(xs), torch.cat(hs), torch.cat(o2s), torch.cat(lacs), torch.cat(causes))


def train_model(use_constraint: bool, tag: str, verbose: bool = True) -> dict:
    fit = calibrate_stoichiometry()

    train_x, train_h, train_o2, train_lac, train_cause = build_dataset(N_TRAIN_PLATES, seed_offset=1000, fit=fit)
    val_x, val_h, val_o2, val_lac, val_cause = build_dataset(N_VAL_PLATES, seed_offset=5000, fit=fit)

    model = PlateGNN()
    flat = train_x.reshape(-1, train_x.shape[-1])
    model.sensor_mean.copy_(flat.mean(dim=0))
    model.sensor_std.copy_(flat.std(dim=0).clamp_min(1e-3))

    # "none" vastly outnumbers the three decline causes (most timesteps are
    # healthy) -- inverse-frequency class weighting so the classifier
    # actually learns the minority classes instead of always predicting
    # "none" and still getting a low loss.
    counts = torch.bincount(train_cause.flatten(), minlength=len(CAUSE_CLASSES)).float()
    cause_class_weight = (counts.sum() / counts.clamp_min(1)).float()
    cause_class_weight = cause_class_weight / cause_class_weight.mean()

    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    loader = DataLoader(TensorDataset(train_x, train_h, train_o2, train_lac, train_cause), batch_size=BATCH_SIZE, shuffle=True)

    history = []
    t0 = time.time()
    for epoch in range(N_EPOCHS):
        model.train()
        epoch_loss = 0.0
        for xb, hb, o2b, lacb, causeb in loader:
            optimizer.zero_grad()
            health_pred, aux_pred, cause_logits = model(xb, PLATE_ADJACENCY, return_cause=True)
            o2_pred, lac_pred = aux_pred[..., 0], aux_pred[..., 1]

            loss = torch.nn.functional.mse_loss(health_pred, hb)
            loss = loss + AUX_WEIGHT * (torch.nn.functional.mse_loss(o2_pred, o2b) + torch.nn.functional.mse_loss(lac_pred, lacb))
            loss = loss + CAUSE_WEIGHT * torch.nn.functional.cross_entropy(
                cause_logits.reshape(-1, len(CAUSE_CLASSES)), causeb.reshape(-1), weight=cause_class_weight,
            )
            if use_constraint:
                loss = loss + CONSTRAINT_WEIGHT * stoichiometric_consistency_penalty(o2_pred, lac_pred, fit)

            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * xb.shape[0]
        epoch_loss /= len(loader.dataset)

        model.eval()
        with torch.no_grad():
            val_health_pred, val_aux_pred, val_cause_logits = model(val_x, PLATE_ADJACENCY, return_cause=True)
            val_loss = torch.nn.functional.mse_loss(val_health_pred, val_h).item()
            val_cause_acc = (val_cause_logits.argmax(dim=-1) == val_cause).float().mean().item()

        history.append({"epoch": epoch, "train_loss": epoch_loss, "val_loss": val_loss, "val_cause_acc": val_cause_acc})
        if verbose and (epoch % 5 == 0 or epoch == N_EPOCHS - 1):
            print(f"[{tag}] epoch {epoch:3d}  train_loss={epoch_loss:.4f}  val_loss={val_loss:.4f}  val_cause_acc={val_cause_acc:.2%}")

    elapsed = time.time() - t0
    ckpt_path = CHECKPOINT_DIR / f"model_{tag}.pt"
    torch.save({
        "model_state": model.state_dict(),
        "fit": fit.__dict__,
        "use_constraint": use_constraint,
        "window": DEFAULT_WINDOW,
    }, ckpt_path)

    meta = {"tag": tag, "use_constraint": use_constraint, "history": history, "elapsed_sec": elapsed, "final_val_loss": history[-1]["val_loss"]}
    with open(CHECKPOINT_DIR / f"train_meta_{tag}.json", "w") as f:
        json.dump(meta, f, indent=2)

    if verbose:
        print(f"[{tag}] done in {elapsed:.1f}s, final val_loss={history[-1]['val_loss']:.4f} -> {ckpt_path}")
    return meta


def load_checkpoint(tag: str = "constrained") -> tuple[PlateGNN, dict]:
    ckpt = torch.load(CHECKPOINT_DIR / f"model_{tag}.pt", weights_only=False)
    model = PlateGNN()
    model.load_state_dict(ckpt["model_state"])
    model.eval()
    return model, ckpt


def calibrate_and_save_bifurcation_threshold(tag: str = "constrained") -> float:
    from backend.gnn.bifurcation import calibrate_threshold

    model, _ = load_checkpoint(tag)
    threshold = calibrate_threshold(model, PLATE_ADJACENCY, WELL_IDS, window=DEFAULT_WINDOW)
    with open(CHECKPOINT_DIR / "bifurcation_threshold.json", "w") as f:
        json.dump({"threshold": threshold, "tag": tag}, f, indent=2)
    print(f"bifurcation threshold calibrated: {threshold:.4f} (from '{tag}' model) -> bifurcation_threshold.json")
    return threshold


if __name__ == "__main__":
    train_model(use_constraint=True, tag="constrained")
    train_model(use_constraint=False, tag="unconstrained")
    calibrate_and_save_bifurcation_threshold(tag="constrained")
